apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.config_map.name }}
data:
  # property-like keys; each key maps to a simple value
  DB_USER: {{ .Values.backend.config_map.db_user }}
  DB_HOST: "{{ .Values.postgres.service.name }}.default.svc.cluster.local"
  DB_PORT: "{{ .Values.postgres.service.port }}"
