apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  labels:
    app: {{ .Values.frontend.app }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app:  {{ .Values.frontend.app }}
  template:
    # pod decliration
    metadata:
      labels:
        app:  {{ .Values.frontend.app }}
    spec:
      containers:
       - name:  {{ .Values.frontend.deployment.name }}
         image: {{ .Values.frontend.deployment.image_name }}:{{ .Values.frontend.deployment.image_tag }}
         ports:
          - containerPort: {{ .Values.frontend.deployment.container_port }}
         envFrom:
          - configMapRef: 
              name: {{ .Values.frontend.config_map.name }}     
      
